version: '3.1'

services:
  backstage:
    image: backstage
    restart: always
    ports:
      - 7007:7007
    volumes:
      - backstage-data:/root/backstage
    networks:
      - backstage-network
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - backstage-data:/var/lib/postgresql/data
    networks:
      - backstage-network

networks:
  backstage-network:


volumes:
  backstage-data:
