version: '3'

services:
  backstage:
    image: backstage
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backstage-network
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - backstage-data:/var/lib/postgresql/data
    networks:
      - backstage-network

networks:
  backstage-network:
volumes:
  backstage-data: