version: '3.1'

services:
  backstage:
    image: backstage
    restart: always
    ports:
      - 7007:7007
    networks:
      - backstage-network
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - backstage-data:/var/lib/postgresql/data
    networks:
      - backstage-network

networks:
  backstage-network:


volumes:
  backstage-data:
